### ISSUE TITLE
SummaryReport

### ISSUE THREAD

**Issue by edmundmiller** [nf-core/viralintegration#28]
### Description of feature

https://github.com/broadinstitute/CTAT-VirusIntegrationFinder/blob/228040dd4ab15ee73b7249698e4a240ad7624e99/WDL/ctat_VIF.wdl#L1198

**Comment by edmundmiller** [comment]
Should also take care of #27

**Comment by edmundmiller** [comment]
@brianjohnhaas hoping you could help with this.

Okay, we're struggling to reproduce the summary_report process. We've taken the inputs from the cromwell execution and set up a test for nextflow. See the test file here: https://github.com/nf-core/viralintegration/blob/summaryreport/tests/modules/summary_report/main.nf.test

We continue to get an error in the first script
```
    Error: Can't rename columns that don't exist.
    x Column `adj_total` doesn't exist.
```
And it appears the `adj_total` column doesn't exist in the cromwell execution **or** in the nextflow execution. However, the cromwell pipeline successfully get's through the summary_report. There's several other missing columns as well that fail if we remove the `adj_total`.

Steps to reproduce:

```
git clone https://github.com/nf-core/viralintegration.git && cd viralintegration
curl -s https://get.nextflow.io | bash 
curl -fsSL https://code.askimed.com/install/nf-test | bash
./nf-test test --profile=docker
```

**Comment by brianjohnhaas** [comment]
Hi Edmund,

I wonder if there's a slight disconnect between the workflow you're running and our latest code  and WDL.  Attached is the version of the file produced in our current code and gets input to the SummaryReport task.  This earlier part of the workflow likely changed a bit in the most recent release.  Note, this latest release should be fairly stable. It's what we're aiming to publish on.
[test.vif.init.filtered.abridged.tsv.gz](https://github.com/nf-core/viralintegration/files/9965212/test.vif.init.filtered.abridged.tsv.gz)
