### ISSUE TITLE
Create dummy fastq data for testing

### ISSUE THREAD

**Issue by allaway** [nf-core/viralintegration#3]
### Description of feature

Perhaps we can pick a virus - say HPV1 - and a couple of human reads - and generate paired fastq.gz files for testing. 

I considered reusing https://github.com/nf-core/test-datasets/tree/sarek/testdata/dummy but I expect we'll want something with both human and viral sequences.

**Comment by edmundmiller** [comment]
There's one possibly floating around here:
https://github.com/bioinformaticsdotca/BiCG_2019

There's also test data in https://github.com/broadinstitute/CTAT-VirusIntegrationFinder/tree/a27faf55cfa9dcc9f4fffa107d05bc9e1c7d82ed/testing. So I think for now we just need to wire that up, and we can move it to nf-core/test-datasets if we need to make changes.

**Comment by edmundmiller** [comment]
https://data.broadinstitute.org/Trinity/CTAT_RESOURCE_LIB/__genome_libs_pre-StarFv1.3/
Actual fasta and gtf
