### ISSUE TITLE
Use a small human reference for test data

### ISSUE THREAD

**Issue by edmundmiller** [nf-core/viralintegration#31]
### Description of feature

Use something like rnaseq's references. Depends on what chr the reads are coming from.

**Comment by edmundmiller** [comment]
Going to need chr 6,11,18

**Comment by Emiller88** [comment]
18 => 13?

**Comment by edmundmiller** [comment]
https://crashcourse.housegordon.org/split-fasta-files.html

**Comment by edmundmiller** [comment]
`cat chr6.fa chr11.fa chr18.fa > GRCh38.chr6-11-18.fa`
`pigz GRCh38.chr6-11-18.fa`

I had to edit the fasta names to be something like:

```
> chr6 blahblahblah
NNNNN....
```

**Comment by edmundmiller** [comment]
Create a gtf with only those 3 chr https://www.biostars.org/p/472553/

**Comment by alyssa-ab** [comment]
Box: https://utdallas.box.com/s/xwa56zk2xa7ckxebki97m1ec109j1b45
nf-core: https://github.com/nf-core/test-datasets/tree/viralintegration/testdata
