### ISSUE TITLE
Loop in results to multiqc

### ISSUE THREAD

**Issue by edmundmiller** [nf-core/viralintegration#32]
### Description of feature

Samtools, STAR, etc.

**Comment by alyssa-ab** [comment]
RNAseq example: https://github.com/nf-core/rnaseq/blob/e049f51f0214b2aef7624b9dd496a404a7c34d14/workflows/rnaseq.nf#L760-L803

https://multiqc.info/docs/

**Comment by alyssa-ab** [comment]
RNAseq `MULTIQC_TSV_FAIL_TRIMMED`
https://github.com/nf-core/rnaseq/blob/e049f51f0214b2aef7624b9dd496a404a7c34d14/workflows/rnaseq.nf#L238-L274
