### ISSUE TITLE
STAR Failure - roll back version

### ISSUE THREAD

**Issue by alyssa-ab** [nf-core/viralintegration#55]
### Description of the bug

`STAR_GENOME_GENERATE_HOST` and `STAR_ALIGN_PLUS` failing on full size HPC runs
Rolled back to STAR 2.7.9a - runs through `STAR_ALIGN_PLUS` then terminates

Look into all STAR versions and containers matching
STAR update commit: [41e30ab](https://github.com/nf-core/viralintegration/commit/41e30ab9c9bcc51c1c7444d3cf0cbbc1a67d5ec9)

### Command used and terminal output

```console
STAR_GENOME_GENERATE_HOST Command Error:
Genome_genomeGenerate.cpp:286:genomeGenerateL exiting because of *OUTPUT FILE* error: could not write the output file star//SA_7
fail()=1 ; bad()=1
Error while trying to write chunk # 0; 0 bytes
File size full = 7233921128 bytes
File size on disk = 173015040 bytes
Solution: check that you have enough space on the disk
Empty space on the disk = 234018081603584 bytes

STAR_ALIGN_PLUS Command Error (after rollback to STAR 2.7.9a):
EXITING because of FATAL ERROR: number of bytes expected from the BAM bin does not agree with the actual size on disk: Expected bin size=3772293264 ; size on disk=1684748073 ; bin number=45
```

### System information

Failing version of STAR 2.7.10a
Rollback to STAR 2.7.9a

**Comment by edmundmiller** [comment]
Might be caused by https://github.com/alexdobin/STAR/issues/1763
